@startsalt
scale 2
{^
Create Account
First Name | "Enter text here "
Last Name | "Enter text here "
Phone Number | "Enter text here "
Email | "Enter text here "
Password | "Enter text here "
[Cancel]|[    Done     ]
}
@endsalt