@startsalt

{
{^
Create Account
First Name | "Enter text here "
Last Name | "Enter text here "
Phone Number | "Enter text here "
Email | "Enter text here "
Password | "Enter text here "
} |
{
"Enter logo here"
}
{
[Cancel]|[    Done     ]
}
}
@endsalt